apiVersion: v1
kind: Pod # k8sのリソースの種類を指定する属性
metadata: # name属性で、指定した値がこのリソースの名称として利用
  name: simple-echo 
spec: #リソースを定義するための属性（Podの場合はPodを構成するコンテナ群をcontainerとして定義する）
  containers:
  - name: nginx # コンテナ名
    image: gihyodocker/nginx:latest
    env:
    - name: BACKEND_HOST
      value: localhost:8080
    ports:
    - containerPort: 80
  - name: echo
    image: gihyodocker/echo:latest
    ports:
    - containerPort: 8080
