version: '2'
services:
  app:
    # app用のDockerfileのパスを記載
    build: .
    image: springboot-part2:0.0.1
      # ポートを公開（expose）します。
      # ホストとポートを指定（ホスト:コンテナ）するか、コンテナのポートのみ指定します（ホスト側のポートはランダムに選ばれます）。
    ports:
        - "8086:8080"
    volumes:
        - .:/app
    environment:
        JAR_TARGET: part2.jar
    command: bash -c
        'cd /app &&
        source "/usr/local/sdkman/bin/sdkman-init.sh" &&
        gradle build &&
        java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app/build/libs/app.jar'

