version: '2'

networks:
  bridge:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: spring-mongodb
    environment:
      -  'MONGODB_USER=user'
      -  'MONGODB_PASS=password!'
    volumes:
      - 'mongodb-data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles

  mongo-express:
    container_name: mongo-express
    links:
      - 'mongodb:mongo'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password!'
    image: mongo-express

  app:
    # app用のDockerfileのパスを記載
    build: .
    image: springboot2:0.0.1
    # ポートを公開（expose）します。
    # ホストとポートを指定（ホスト:コンテナ）するか、コンテナのポートのみ指定します（ホスト側のポートはランダムに選ばれます）。
    ports:
      - "8086:8080"
    links:
      - mongodb #連携するシステムを指定

volumes:
  mongodb-data: {}


