version: '2.1'

services:
  # mysql
  mysql-test:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      # databaseの永続的なストレージを設定
      # ${volumesに定義したkey}:{マウントパス}
      # 下記で作成した、mysql-dataに「/var/lib/mysql」をマウントさせる
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root #root のパスワード設定
      - MYSQL_DATABASE=test2 #database の作成
      - MYSQL_USER=sa2 #新規ユーザの作成
      - MYSQL_PASSWORD=password2 #新規ユーザのパスワード設定

  db_data:
    image: busybox
    volumes:
        - /var/lib/mysql

# volumeにlocal（DRIVER）を作成して、volume Nameを「mysql-data」とする。
#volumes:
#  mysql-data:
#    driver: local