version: '2'
services:
  app:
    # app用のDockerfileのパスを記載
    build: .
    image: springboot-part2:0.0.1
      # ポートを公開（expose）します。
      # ホストとポートを指定（ホスト:コンテナ）するか、コンテナのポートのみ指定します（ホスト側のポートはランダムに選ばれます）。
    ports:
        - "8086:7878"
    volumes:
        - .:/app
    environment:
        JAR_TARGET: autoTest-0.0.1.jar
    links:
        - 'mysql-standalone:mysql'

