version: '2'
services:
  app:
    # app用のDockerfileのパスを記載
    build: .
    image: springboot-part2:0.0.1
      # ポートを公開（expose）します。
      # ホストとポートを指定（ホスト:コンテナ）するか、コンテナのポートのみ指定します（ホスト側のポートはランダムに選ばれます）。
    ports:
        - "8086:8080"
        - "8000:8000"
    environment:
        JAR_TARGET: part2.jar
    command: bash -c
        'cd /usr/src/app &&
        source "/usr/local/sdkman/bin/sdkman-init.sh" &&
        java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -jar /app/build/libs/app.jar'

