###  -------------------------------------------------------------------------------------
## 【Dockerfileの基本】
# Dockerfileの用途
# Docker上で動作させるコンテナの構成情報を記述するファイル（Dockerfileからイメージを作成する）

# Dockerfileの基本
# Dockerfileはテキスト形式のファイル(拡張子はなし)
# Dockerfileの書式
# 命令　引数

# 命令について
# FROM : ベースイメージの指定
# MAINTAINER : Dockerfileの作成者情報
# RUN : コマンド実行
# CMD : デーモン実行
# LABEL : ラベル設定
# EXPOSE : ポートのエクスポート
# ENV : 環境変数の設定
# ADD : ファイル/ディレクトリの追加
# COPY : ファイルのコピー
# VOLUME : ボリュームのマウント
# ENTRYPOINT : デーモン実行
# USER : ユーザ指定
# WORKDIR : 作業ディレクトリの指定
# ONBUILD : ビルド完了後に実行される命令

# Dockerfileの作成
# FROM [イメージ名]
# FROM [イメージ名]:[タグ名]
# FROM [イメージ名]@[ダイジェスト]

# Dockerfileの記載
###------------------
# ベースイメージの設定
FROM centos:centos7
###------------------


# Dockerfileの作成者
# MAINTAINER [Dockerfile作成者]

# Dockerfileの記載
###------------------
# MAINTAINERの設定
MAINTAINER testuser
###------------------

# DockerfileからDockerイメージの作成
# docker build -t [生成するイメージ名]:[タグ名][Dockerfileの場所]
docker build -t sample:1.0 ./

# Dockerイメージのレイヤー構造
# Dockerfileの記載
###------------------
# STEP:0 Centos(ベースイメージ)
FROM centos:centos7

# STEP:1 Apacheのインストール
RUN yum install -y httpd

# STEP:2 ファイルのコピー
COPY index.html /var/www/html

# STEP:3 Apacheの起動
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
###------------------

###  -------------------------------------------------------------------------------------
## 【コマンド/デーモンの実行】
# コマンドの実行(RUN命令)
# RUN [実行したいコマンド]
RUN yum -y install httpd # Shell形式での記述
RUN ["/bin/bash", "-c", "yum -y install httpd"] # Exec形式での記述
# docker history sample:1.0 (Docderfile利用時に何が実行されたか確認する)


# デーモンの実行(CMD命令)
# CMD [実行したいコマンド]
CMD /usr/sbin/httpd -D FOREGROUND # Shell形式での記述
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"] # Exec形式での記述

# Dockerfileの記載(ENTRYOINT命令のパラメータとしての記述)
###------------------
# STEP:0 Centos(ベースイメージ)
FROM centos:centos7

# MAINTAINERの記載
MAINTAINER testuser

# httpdのインストール
RUN ["yum", "install", "-y", "httpd"]

# httpdの実行
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
###------------------

# デーモンの実行(ENTRYPOINT命令)
# ENTRYPOINT命令で指定したコマンドは、DockerfileからビルドしたイメージからDockerコンテナを起動するため、docker runコマンドを実行した時に実行される
# ENTRYPOINT [実行したいコマンド]
ENTRYPOINT /usr/sbin/httpd -D FOREGROUND # Shell形式での記述
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"] # Exec形式での記述
ENTRYPOINT /usr/sbin/nginx -g "daemon off" # Shell形式での記述(nginx)

#### ENTRYPOINTとCMD命令の違い
## CMD命令
#   docker runコマンド実行じにデーモンとして実行するコマンドを指定すると、コンテナ実行時にDockerfileよりもコマンドを優先する。
## ENTRYPOINT命令
#   コンテナ実行時に起動させたいデーモンを強制的に指定する。

# ビルド完了後に実行される命令（ONBUILD命令）
# Dockerfile(ONBUILD記載) -> baseimage -> Dcokerfile(baseimage利用) -> newimage(このタイミングでONBUILDコマンドが実行される)
# ONBUILD [実行したいコマンド]
ONBUILD RUN echo "ONBUILDはsampleイメージのDockerfileに記載しています"

# ONBUILDサンプルの例について
# Dockerfile.base -> web-base(baseイメージ作成)
tar cvf website.tar website.html # htmlをtarに固める
docker build -t web-base -f Dockerfile.base .
docker build -t web-iamge .
docker run -d -p 80:80 web-iamge
docker inspect --format="{{.Config.OnBuild}}" web-base
# アクセス localhost:80/website.html


###  -------------------------------------------------------------------------------------
## 【環境/ネットワークの設定】
# 環境変数の設定(ENV命令)
# ENV [キー名] [値]
ENV myName "TESTTESTUSER"
ENV myOrder GIN Whisky Calvados
ENV myNickName "TUSER"

# ENV [キー名]=[値]
ENV myName="TESTTESTUSER" \
	myOrder=GIN Whisky Calvados \
	myNickName="TUSER"

# 作業ディレクトリの指定(WORKDIR命令)
# WORKDID [作業ディレクトリのパス]
WORKDIR /fisrt
WORKDIR second
WORKDIR third
RUN ["pwd"]

docker build -t testworkid .

# ユーザの指定(USER命令)
# USER [ユーザ名/UID]
RUN ["adduser", "asa"]
RUN ["whoami"]
USER asa
RUN ["whoami"]

# ラベルの指定(LABEL命令)
# LABEL キー名 = 値
LABEL title="WebAPServerImage"
LABEL version="1.0"
LABEL description="This image is WebAPServer for SpringBoot"

docker build -t sample2 .
docker inspect --format="{{.Config.Labels}}" sample2 #sample2イメージのラベルを確認

# ポートの設定(EXPOSE命令) コンテナの公開するポート番号を指定する
EXPOSE 8080

###  -------------------------------------------------------------------------------------
## 【ファイルシステムの設定】
# ファイル/ディレクトリの追加(ADD命令)
# ADD ホストのファイルパス Dockerイメージのファイルパス
# ADD ["ホストのファイルパス" "Dockerイメージのファイルパス"]
ADD host.html /docker_dir/ #ホストのhtmlファイルをdockerの指定のディレクトリにコピー

# 利用方法
WORKDIR /docker_dir
ADD website.html web/

# ファイルのコピー(COPY命令)
# COPY ホストのファイルパス Dockerイメージのファイルパス
# COPY ["ホストのファイルパス" "Dockerイメージのファイルパス"]

# ボリュームのマウント(VOLUM命令)
# VOLUME ["/マウントポイント"]

# 利用方法------------------------------------------
# Dockerfileの記載(ENTRYOINT命令のパラメータとしての記述)
###------------------
# STEP:0 Centos(ベースイメージ)
FROM centos:centos7

# MAINTAINERの記載
MAINTAINER testuser

# ボリュームの作成（Apache httpdのログを管理したいので、デフォルトのログ保存先を指定）
RUN ["mkdir", "var/log/httpd"]
VOLUME /var/log/httpd
###------------------

docker build -t log-image .
docker run -it --name log-container log-image

# Dockerfileの記載(ENTRYOINT命令のパラメータとしての記述)
###------------------
# STEP:0 Centos(ベースイメージ)
FROM centos:centos7

# MAINTAINERの記載
MAINTAINER testuser

# httpdのインストール
RUN ["yum", "-y", "install", "httpd"]

# httpdの実行
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
###------------------

docker build -t web-image .
docker run -d --name web-container -p 80:80 --volumes-from log-container web-image
# -p 80:80 ホストとコンテナをつなぐ
# --volumes-from log-container log-containerで指定したコンテナの[Data Volume]を全部マウントしてコンテナを起動
		
docker start -ia log-container

###  -------------------------------------------------------------------------------------
## 【Dockerイメージの自動生成/公開】GITHUBの1リポジトリ単位でDockerイメージを作成する
# Automated Buildの流れ
# 

# GitHubへの公開
# 

# Docker Hubのリンク設定 
# 

# Dockerfileのビルド
# 

# Dockerイメージの確認
# 

docker build -t restapi-mysql ./
docker-compose up



















